---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: all
  gather_facts: False
  sudo: True
  vars:
    app_home: /opt/aert
    app_env: 
    app_assets:
    app_uploads:
    app_logs:

  roles:
    - common
    - web-app

