# -*- mode: ruby; -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Debian Wheezy
  config.vm.box = "wheezy64"
  config.vm.box_url = "https://dl.dropboxusercontent.com/s/xymcvez85i29lym/vagrant-debian-wheezy64.box"

  # Network
  config.vm.network :private_network, ip: "192.168.111.222"
  config.vm.hostname = "vagrant.webfolder.org"
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
  config.vm.network :forwarded_port, guest: 5432, host: 5432

  config.vm.synced_folder "../", "/home/vagrant/PROJECT"

  # Customize the box
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 512]
  end

end

