# -*- mode: ruby; -*-
# vi: set ft=ruby :

# Installer local path <without> extension
INSTALLER_VERSION = IO.read("../RELEASE-VERSION").rstrip
INSTALLER_PATH = File.join(File.dirname(__FILE__), "..", "build", "setup_aert-webfolder_" + INSTALLER_VERSION)

Vagrant.configure("2") do |config|
  # Debian Wheezy
  config.vm.box = "wheezy64"
  #config.vm.box_url = "https://dl.dropboxusercontent.com/s/xymcvez85i29lym/vagrant-debian-wheezy64.box"
  config.vm.box_url = "http://downloads.shadoware.org/wheezy64.box"

  # Network
  config.vm.network :private_network, ip: "192.168.111.223"
  config.vm.hostname = "webfolder.devaert.org"
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
  config.vm.network :forwarded_port, guest: 5432, host: 5432

  config.vm.synced_folder "../", "/home/vagrant/PROJECT"

  # Provision
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.inventory_path = "ansible/inventory.ini"
    ansible.extra_vars = { installer_local: INSTALLER_PATH, }
  end

  # Customize the box
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 512, "--name", "aert-webfolder"]
  end

end

