---

# Install requirements

- name: app_webfolder-apt
  apt: pkg=$item state=installed
  with_items:
    - python-virtualenv
    - python-pip


# Create VirtualEnv

#TODO

# Install wheel requirements

#TODO

# Get Git sources

- name: /srv/www/apps
  file: path=/srv/www/apps state=directory owner=www-data group=www-data

- name: app_webfolder_git
  git: repo=https://github.com/aert/aert-webfolder.git dest=/srv/www/apps/aert-webfolder.git update=yes force=yes

# Migrate db

#TODO

# Configure gunicorn

- name: app_webfolder_gunicorn-config
  template: src=uwsgi.ini.j2 dest=/etc/uwsgi/apps-available/webfolder.ini
  notify:
    - restart uwsgi

- name: app_webfolder_uwsgi-enable
  file: src=/etc/uwsgi/apps-available/webfolder.ini dest=/etc/uwsgi/apps-enabled/webfolder.ini state=link
