---

# Install requirements
- name: app_webfolder-apt
  apt: pkg=$item state=installed
  with_items:
    - python-virtualenv
    - python-pip


# Create Dirs
- name: app-dirs
  file: path=$item state=directory owner=www-data group=www-data
  with_items:
    - "$prefix"
    - "$tmp_path"

# Upload & Install Installer
- name: app-installer-upload
  copy: src=$installer_tgz dest=${tmp_path} owner=www-data group=www-data

- name: app-installer-untar
  shell: cd ${tmp_path} && tar zxf {{installer_tgz|basename}}

- name: app-installer-install
  shell: cd ${tmp_path}/{{installer_dirname}} && make install PREFIX=/opt/aert

- name: app-installer-clean
  file: path=${tmp_path}/{{installer_dirname}} state=absent

# Config Dirs 
- name: app-dirs-app
  file: path=$item state=directory owner=www-data group=www-data
  with_items:
    - "$app_assets"
    - "$app_uploads"
    - "$app_log"

- name: app-installer-install
  shell: chown -R www-data:www-data ${app_home}

# Install wheel requirements

#TODO

# Init folder structure


# Migrate db

#TODO

# Configure gunicorn
#- name: app-gunicorn
#  template: src=start_gunicorn.sh.j2 dest=$app_home/start_gunicorn.sh
#  notify:
#    - restart nginx

#- name: app_webfolder_uwsgi-enable
#  file: src=/etc/uwsgi/apps-available/webfolder.ini dest=/etc/uwsgi/apps-enabled/webfolder.ini state=link
