---
# Install Nginx & web app

- name: nginx-apt
  apt: pkg=$item state=installed
  with_items:
    - nginx
  tags: nginx

# Directories & files

- name: nginx-user
  user: name=www-data state=present home=/srv/www

- name: nginx-rm-default
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: nginx-/srv/www
  file: path=/srv/www state=directory owner=www-data group=www-data
        
- name: nginx-/etc/nginx/sites-available
  file: path=/etc/nginx/sites-available state=directory owner=root mode=0755

- name: nginx-/etc/nginx/sites-enabled
  file: path=/etc/nginx/sites-enabled state=directory owner=root mode=0755

 

- include: app_webfolder.yml tags=app
- include: supervisor.yml tags=app
